import { createClient } from"@/lib/supabase/server";
import Link from"next/link";


export const dynamic ='force-dynamic';

export default async function HistoryPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return <div>Please log in</div>;
  }

  // Fetch RFQ history for this buyer (without invalid join)
  const { data: historyRows, error } = await supabase
    .from("rfq_history")
    .select(`id, vendor_id, product_name, quantity, price_per_unit, saved_amount, priority, created_at`)
    .eq("buyer_id", user.id)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching RFQ history:", error);
  }

  const history = historyRows || [];

  // Fetch vendor names manually since FK points to auth.users instead of profiles
  const vendorIds = [...new Set(history.map(h => h.vendor_id))];
  let companyMap: Record<string, string> = {};
  
  if (vendorIds.length > 0) {
    const { data: profiles } = await supabase
      .from("profiles")
      .select("id, company_name")
      .in("id", vendorIds);
      
    if (profiles) {
      companyMap = profiles.reduce((acc, p) => ({ ...acc, [p.id]: p.company_name ||"Unknown Vendor" }), {});
    }
  }

  const enhancedHistory = history.map(h => ({
    ...h,
    vendor: { company_name: companyMap[h.vendor_id] ||"Unknown Vendor" }
  }));

  const totalSaved = enhancedHistory.reduce((sum, item) => sum + Number(item.saved_amount), 0);
  const totalSpend = enhancedHistory.reduce((sum, item) => sum + (Number(item.price_per_unit) * Number(item.quantity)), 0);

  return (
    <div className="p-8 max-w-6xl mx-auto animate-[fadeUp_0.4s_ease-out_both]">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className={`text-3xl text-stone-900`}>Procurement History</h1>
          <p className="mt-2 text-stone-500">Track your past orders and total savings generated by AI recommendations.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
        <div className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm">
          <p className="text-sm font-medium text-stone-500 mb-1">Total RFQs Awarded</p>
          <p className={`text-3xl text-stone-900`}>{history?.length || 0}</p>
        </div>
        <div className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm">
          <p className="text-sm font-medium text-stone-500 mb-1">Total Spend</p>
          <p className={`text-3xl text-stone-900`}>₹{totalSpend.toLocaleString()}</p>
        </div>
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10 text-6xl">💰</div>
          <p className="text-sm font-medium text-emerald-800 mb-1">Total Saved vs Average</p>
          <p className={`text-3xl text-emerald-700`}>₹{totalSaved.toLocaleString()}</p>
        </div>
      </div>

      <div className="rounded-2xl border border-stone-200 bg-white overflow-hidden shadow-sm">
        <div className="p-5 border-b border-stone-200 bg-stone-50">
          <h2 className="font-semibold text-stone-900">Past Orders</h2>
        </div>
        
        {(!enhancedHistory || enhancedHistory.length === 0) ? (
          <div className="p-10 text-center text-stone-500">
            {error ?`Error: ${error.message}` :"You haven't awarded any RFQs yet."}
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-white text-stone-500 border-b border-stone-100">
                <tr>
                  <th className="px-6 py-4 font-medium">Date</th>
                  <th className="px-6 py-4 font-medium">Product / Query</th>
                  <th className="px-6 py-4 font-medium">Vendor</th>
                  <th className="px-6 py-4 font-medium">Qty</th>
                  <th className="px-6 py-4 font-medium">Unit Price</th>
                  <th className="px-6 py-4 font-medium text-right">Savings</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100">
                {enhancedHistory.map((item) => (
                  <tr key={item.id} className="transition-colors hover:bg-stone-50/50">
                    <td className="px-6 py-4 text-stone-600">
                      {new Date(item.created_at).toLocaleDateString("en-IN", { month:"short", day:"numeric", year:"numeric" })}
                    </td>
                    <td className="px-6 py-4 font-medium text-stone-900">
                      {item.product_name}
                      <div className="text-xs text-stone-400 mt-0.5 font-normal">Priority: {item.priority.replace('_','')}</div>
                    </td>
                    <td className="px-6 py-4 text-stone-800">
                      {Array.isArray(item.vendor) ? item.vendor[0]?.company_name : item.vendor?.company_name ||"Unknown Vendor"}
                    </td>
                    <td className="px-6 py-4 text-stone-600">{item.quantity}</td>
                    <td className="px-6 py-4 text-stone-600">₹{item.price_per_unit.toLocaleString()}</td>
                    <td className="px-6 py-4 text-right">
                      {item.saved_amount > 0 ? (
                        <span className="inline-flex items-center px-2.5 py-1 rounded-md bg-emerald-100 text-emerald-800 font-medium text-xs">
                          + ₹{Number(item.saved_amount).toLocaleString()}
                        </span>
                      ) : (
                        <span className="text-stone-400">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <style>{`
        @keyframes fadeUp { from {opacity:0;transform:translateY(12px)} to {opacity:1;transform:translateY(0)} }
`}</style>
    </div>
  );
}
